version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Magick.NET-Q16-AnyCPU"
        update-types:
          - "version-update:semver-patch"
